### ISSUE TITLE
Make an exception for subpages of GPUSupportedLimits

### ISSUE THREAD

**Issue by Elchi3** [dontcallmedom/mdn-gaps#7]
https://developer.mozilla.org/en-US/docs/Web/API/GPUSupportedLimits doesn't have sub pages for its properties because it would be quite an overhead to do that. There is a table on the main interface page instead listing the values.

mdn-gaps reports the missing sub pages and I think we should make an exception here.

**Comment by teoli2003** [comment]
Should we have a file with a specific format for these exceptions (like the ones about WebGL, DOM(ReadOnly)Matrix, or OffscreenCanvasRenderingContext2D and others)? Other tools may have a similar need (not creating a link to MDN for these features).

But this may be outside the scope of this issue.

**Comment by dontcallmedom** [comment]
> Should we have a file with a specific format for these exceptions (like the ones about WebGL, DOM(ReadOnly)Matrix, or OffscreenCanvasRenderingContext2D and others)? Other tools may have a similar need (not creating a link to MDN for these features).

FWIW, exceptions are managed through a [declarative JSON file](https://github.com/dontcallmedom/mdn-gaps/blob/main/annotations.json), so it should be relatively easy to move the data to an MDN-maintained list, and adapt the tool to use that separate list

**Comment by teoli2003** [comment]
Perfect. This JSON file works well for now. I will likely add some more entries later this Quarter.
